name: my_flutter
description: "一个新的Flutter项目。"
# 防止包被意外发布到pub.dev
# 使用`flutter pub publish`时。这对私有包来说是首选。
publish_to: 'none' # 如果你想发布到pub.dev，请移除这行

# 定义应用的版本和构建号。
# 版本号由三个数字组成，如 1.2.43，通过点连接。
# 可以添加一个可选的构建号，通过+分隔。
# 在执行flutter build时，可以通过--build-name和--build-number参数覆盖版本号和构建号。
# 在Android中，build-name用作versionName，build-number用作versionCode。
# 更多关于Android版本控制的信息，请访问 https://developer.android.com/studio/publish/versioning
# 在iOS中，build-name用作CFBundleShortVersionString，build-number用作CFBundleVersion。
# 更多关于iOS版本控制的信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在Windows中，build-name用作产品和文件版本的主要、次要和修订部分，build-number用作构建后缀。
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# 依赖项指定了包为了正常工作需要的其他包。
# 可以运行`flutter pub upgrade --major-versions`自动将包依赖项升级到最新版本，或者，
# 通过将下面的版本号更改为pub.dev上可用的最新版本来手动更新依赖项。要查看哪些依赖项有新版本可用，运行`flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 添加Cupertino Icons字体到你的应用。
  # 与CupertinoIcons类一起使用以获得iOS风格的图标。
  cupertino_icons: ^1.0.6
  # flutter_swiper: ^1.1.5 # 图片轮滑

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3        # http请求库
  fluttertoast: ^8.0.8 # toast库
  carousel_slider: ^4.0.0 #  轮播图库
  url_launcher: ^6.0.20  # url跳转库
  geolocator: ^8.0.0 # 定位
  flutter_blue: ^0.8.0 # BLE蓝牙
#  flutter_bluetooth_serial: ^0.3.2 # 经典蓝牙
#  flutter_blue_classic: 0.0.2 # 经典蓝牙
  image_picker: ^1.1.1  # 选择图片（相机、相册）
  file_picker: ^4.0.0 # 文件选择
  shared_preferences: ^2.0.6 # 缓存
  dio: ^5.4.3+1 # http请求
  flutter_staggered_grid_view: ^0.7.0 # 瀑布流
  bluetooth_classic: ^0.0.1
  # "flutter_lints"包包含了一套推荐的lint规则，
  # 以鼓励良好的编码实践。该包提供的lint集在你的
  # 包的根目录下的`analysis_options.yaml`文件中被激活。
  # 查看该文件了解如何停用特定的lint规则和激活额外的规则。
  flutter_lints: ^3.0.0

# 关于这个文件的通用Dart部分的信息，请查看
# 下面的页面：https://dart.dev/tools/pub/pubspec

# 特定于Flutter包的部分。
flutter:

  # 确保Material Icons字体包含在你的应用中，
  # 这样你就可以在material Icons类中使用这些图标。
  uses-material-design: true

  # 要添加资源到你的应用，添加一个assets部分，如下所示:
  assets:
    - assets/images/logo.jpg
    - assets/images/wechat.png
    - assets/images/apple.png

  # 图片资源可以指向一个或多个分辨率特定的"variants"，详情见
  # https://flutter.dev/assets-and-images/#resolution-aware

  # 关于从包依赖中添加资源的详情，请见
  # https://flutter.dev/assets-and-images/#from-packages
  # 要在你的应用中添加自定义字体，请在这里的"flutter"部分添加一个fonts部分，
  # 每个条目应该有一个"family"键，带有字体家族名称，和一个"fonts"键，
  # 列出字体的资源和其他描述符。例如:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
